[mouse click settings]
#  This section defines the mouse click settings for the application.
#  Time limits are in milliseconds
#  Note the unconventional syntax allowing spaces. This is for the benefit
#  of the non-developer users editing this file manually. The machinery
#  reading the settings, immediately translates them into camelCase. For
#  example, "press time limit" becomes "pressTimeLimit" and "mouse click
#  settings" in the section header becomes "mouseClickSettings" in the code.
#  Please note that the companion file 'settings.types' is json formatted
#  and requires the camelCase syntax. Changes to the types file is not
#  intended to ever be changed post deployment.
press time limit = 100
release time limit = 100
hold time limit = 500
#  Radii are in pixels
press radius = 5
release radius = 5
hold radius = 10

[example]
never gonna give you up = 69
never gonna let you down = 420
never gonna run around and desert you = 1337
never gonna make you cry = 80085
never gonna say goodbye = 8008135
