"""
TestAlignum subclasses 'QeeNumTest' and provides tests for the 'Alignum'
class from the 'worQt.utils.qee_num' module.
"""
#  AGPL-3.0 license
#  Copyright (c) 2026 Asger Jon Vistisen
from __future__ import annotations

from typing import TYPE_CHECKING

from icecream import ic
from worktoy.utilities import textFmt

from worQt.utils.geom import Rect, Point2D, Size
from worQt.utils.qee_num import Alignum, HAlignum, VAlignum

from . import QeeNumTest
from tests import RectSampler

if TYPE_CHECKING:  # pragma: no cover
  from typing import Any, Union, Optional, TypeAlias, Type


class TestAlignum(QeeNumTest):
  """
  TestAlignum subclasses 'QeeNumTest' and provides tests for the 'Alignum'
  class from the 'worQt.utils.qee_num' module.
  """

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #  NAMESPACE  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  #  Public Variables
  staticRectSampler = RectSampler(0, 31, 256, 511)
  moveRectSampler = RectSampler(32, 63, 128, 255 - 64)

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #  PARENT METHODS   # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  @classmethod
  def setUpClass(cls, ) -> None:
    """
    This method is called once before all tests in this class. It can be used
    to set up any state that is shared across tests.
    """
    super().setUpClass()

  def setUp(self, ) -> None:
    """
    This method is called before each test method. It can be used to set up
    any state that is specific to each test.
    """
    super().setUp()
    self.staticRectSampler.rowCount = 8
    self.staticRectSampler.colCount = 8
    self.moveRectSampler.rowCount = 8
    self.moveRectSampler.colCount = 8

  def assertAlmostEqual(self, *args, **kwargs) -> None:
    left, right, *rest = args
    if isinstance(left, Point2D) and isinstance(right, Point2D):
      self.assertTrue(abs(left.x - right.x) < 2)
      self.assertTrue(abs(left.y - right.y) < 2)
    elif isinstance(left, Size) and isinstance(right, Size):
      self.assertTrue(abs(left.width - right.width) < 2)
      self.assertTrue(abs(left.height - right.height) < 2)
    elif isinstance(left, Rect) and isinstance(right, Rect):
      self.assertAlmostEqual(left.topLeft, right.topLeft)
      self.assertAlmostEqual(left.size, right.size)
    else:
      super().assertAlmostEqual(*args, **kwargs)

  def test_by_orientation(self, ) -> None:
    """
    This method tests the 'horizontal' and 'vertical' properties of the
    'Alignum' class.
    """
    for alignum in Alignum:
      name = str.replace(alignum.name, '_', '')
      name = str.replace(name, alignum.vertical.name, '')
      name = str.replace(name, alignum.horizontal.name, '')
      self.assertFalse(name)

  def test_combine(self, ) -> None:
    """
    This method tests the 'combine' class method of the 'Alignum' class.
    """
    for hAlign, vAlign in zip(HAlignum, VAlignum):
      if hAlign is vAlign:
        continue
      wrongOrderAlignum = Alignum.combine(hAlign, vAlign)
      alignum = Alignum.combine(vAlign, hAlign, )
      self.assertIs(alignum, wrongOrderAlignum)
      self.assertEqual(alignum.horizontal, hAlign)
      self.assertEqual(alignum.vertical, vAlign)
      name = str.replace(alignum.name, '_', '')
      name = str.replace(name, hAlign.name, '')
      name = str.replace(name, vAlign.name, '')
      self.assertFalse(name)

  def test_rect_samplers(self, ) -> None:
    """
    This method tests the 'Rect' objects generated by the 'RectSampler'
    samplers at 'staticRectSampler' and 'moveRectSampler'. The 'Rect'
    objects generated by the former is expected to fully contain the
    'Rect' objects generated by the latter.
    """
    for staticRect in self.staticRectSampler.row:
      for moveRect in self.moveRectSampler.row:
        self.assertIsInstance(staticRect, Rect)
        self.assertIsInstance(moveRect, Rect)
        self.assertIn(moveRect, staticRect)

  def test_apply_rect_rect(self, ) -> None:
    """
    This method tests the 'apply' method on the overload for 'Rect' to
    'Rect'.
    """

    appliedDict: dict[Alignum, str] = {
      Alignum.TOP_LEFT     : 'topLeft',
      Alignum.TOP_CENTER   : 'top',
      Alignum.TOP_RIGHT    : 'topRight',
      Alignum.CENTER_LEFT  : 'left',
      Alignum.CENTER       : 'center',
      Alignum.CENTER_RIGHT : 'right',
      Alignum.BOTTOM_LEFT  : 'bottomLeft',
      Alignum.BOTTOM_CENTER: 'bottom',
      Alignum.BOTTOM_RIGHT : 'bottomRight',
      }

    _c = 0

    for staticRect in self.staticRectSampler.row:
      for moveRect in self.moveRectSampler.row:
        for alignum in Alignum:
          appliedRect = alignum.apply(staticRect, moveRect)
          self.assertIsInstance(appliedRect, Rect)
          self.assertEqual(appliedRect.size, moveRect.size)
          overlapKey = appliedDict[alignum]
          appliedOverlap = getattr(appliedRect, overlapKey)
          staticOverlap = getattr(staticRect, overlapKey)
          self.assertAlmostEqual(appliedOverlap, staticOverlap)
          _c += 1
    nRects = self.staticRectSampler.rowCount * self.moveRectSampler.rowCount
    self.assertEqual(_c, nRects * len(Alignum))
