"""
FontStyleNum enumerates the style (slant) of a font.

NORMAL selects the regular upright face. ITALIC requests an italic
face, which may use dedicated glyph designs. OBLIQUE requests a
slanted version of the upright face, either provided by the font or
synthetically generated by the renderer.

Some font families do not distinguish between italic and oblique,
in which case both may resolve to the same visual result.
"""
#  AGPL-3.0 license
#  Copyright (c) 2026 Asger Jon Vistisen
from __future__ import annotations

from typing import TYPE_CHECKING

from PySide6.QtGui import QFont
from worktoy.keenum import KeeNum, Kee
from worktoy.waitaminute.keenum import KeeValueError

from . import FontMeta

if TYPE_CHECKING:  # pragma: no cover
  from typing import Any, Self


class FontStyleNum(KeeNum, metaclass=FontMeta):
  """
  FontStyleNum enumerates the style (slant) of a font.

  NORMAL selects the regular upright face. ITALIC requests an italic
  face, which may use dedicated glyph designs. OBLIQUE requests a
  slanted version of the upright face, either provided by the font or
  synthetically generated by the renderer.

  Some font families do not distinguish between italic and oblique,
  in which case both may resolve to the same visual result.
  """

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #  ENUMERATED MEMBERS   # # # # # # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  NORMAL = Kee[QFont.Style](QFont.Style.StyleNormal)
  ITALIC = Kee[QFont.Style](QFont.Style.StyleItalic)
  OBLIQUE = Kee[QFont.Style](QFont.Style.StyleOblique)

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #  DOMAIN SPECIFIC  # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  @classmethod
  def __class_resolve__(cls, style: Any) -> Self:
    for member in cls:
      if member.value == style.value:
        return member
    raise KeeValueError(cls, style)
