"""
WAction provides a class between 'QAction' and the actions used in
the application. It streamlines initialization providing 'parent', 'name',
'icon' and 'shortcut' as parameters to the constructor. Parents can still
set more advanced features after instantiation, such as 'statusTip'.

  - Arguments:
    shortcut (optional): An shortcut for the action.

  - Autogenerated Properties:
    name (readonly): The name of the action, resolved by 'QtBox'
    parent (readonly): The parent menu, resolved by 'QtBox'
    icon (readonly): The icon of the action, resolved from the name.
"""
#  AGPL-3.0 license
#  Copyright (c) 2025 Asger Jon Vistisen
from __future__ import annotations

from typing import TYPE_CHECKING

from PySide6.QtCore import QKeyCombination
from PySide6.QtGui import QAction, QKeySequence, QShortcut
from PySide6.QtWidgets import QWidget

from worktoy.dispatch import overload
from worktoy.waitaminute import VariableNotNone

from ..core import WBaseObject
from ..res import getIcon, getShortCut

if TYPE_CHECKING:  # pragma: no cover
  from typing import Optional, Union, TypeAlias

  _Cuts = Union[QKeySequence, QKeyCombination, str, QShortcut]
  Cut: TypeAlias = Optional[_Cuts]


class WAction(QAction, WBaseObject):
  """
  WAction provides a class between 'QAction' and the actions used in
  the application. It streamlines initialization providing 'parent', 'name',
  'icon' and 'shortcut' as parameters to the constructor. Parents can still
  set more advanced features after instantiation, such as 'statusTip'.
  """

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #  NAMESPACE  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  #  Class Variables

  #  Fallback Variables

  #  Private Variables
  __action_name__ = None

  #  Public Variables

  #  Virtual Variables

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #  GETTERS  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #  SETTERS  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  def _setActionName(self, name: str, ) -> None:
    if self.__action_name__ is not None:
      raise VariableNotNone('self.__action_name__', self.__action_name__)
    self.__action_name__ = name
    QAction.setIcon(self, getIcon(name))
    QAction.setShortcut(self, getShortCut(name))

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #  SIGNALS  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #  Python API   # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #  CONSTRUCTORS   # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  @overload(str)
  def __init__(self, name: str) -> None:
    QAction.__init__(self, )
    QAction.setText(self, str.capitalize(name, ))
    QAction.setObjectName(self, name)
    self._setActionName(name)

  @overload(str, QWidget)
  def __init__(self, name: str, parent: QWidget) -> None:
    QAction.__init__(self, parent)
    self._setActionName(name)
    QAction.setText(self, str.capitalize(name, ))
    QAction.setObjectName(self, name)

  @overload(QWidget, str)
  def __init__(self, parent: QWidget, name: str) -> None:
    QAction.__init__(self, parent)
    self._setActionName(name)
    QAction.setText(self, str.capitalize(name, ))
    QAction.setObjectName(self, name)
